### ISSUE TITLE
ColorPicker will not show when clicked inside an NSTableViewCell

### ISSUE THREAD

**Issue by miscampbell** [DrummerB/BFColorPickerPopover#5]
Hi 

I am having an issue where the ColorPicker will not display when clicked inside an NSTableView. From debugging the issue I see that the method: 
- (void)_performActivationClickWithShiftDown:(BOOL)shift inside NSColorWell+BFColorPickerPopover.m

Is not being called when the mouseDown event is fired inside BFPopoverColorWell.m.

I have tried changing the mouseDown event to always call:
[self deactivate];
[self activateWithPopover];

This fixed the issue of the Popover not displaying but introduced a different issue that when I clicked onto a another NSColorWell without dismissing the ColorPickerPopover the colour would change both NSColorWells to be the same colour.

Can you please help me to understand how I cold possibly fix this issue ?

Thanks,
Michael

**Comment by DrummerB** [comment]
Hi,

do you have a simple project that demonstrates this problem? I just tried and I can't reproduce it, it works fine for me. Thanks.
