### ISSUE TITLE
BFColorPickerPopover is not disappearing

### ISSUE THREAD

**Issue by Mediajon** [DrummerB/BFColorPickerPopover#7]
BFColorPickerPopover is not disappearing after selecting color.

**Comment by DrummerB** [comment]
It's not supposed to disappear. You can make it disappear by clicking anywhere outside the popover, or by pressing Esc. How would you expect it to work instead?

**Comment by Mediajon** [comment]
Is it possible to make it disappear after selecting color, without clicking anywhere or pressing ESC? There is a set background button, after selecting background color, is it possible to make disappear popover window?

**Comment by DrummerB** [comment]
What do you mean by "after selecting a color"? Color selection is a continuous process. For instance if you're using the RGB sliders, when would you consider to be done with selecting a color? You move around any of the 3 sliders, changing the color instantly. I don't quite understand what you're trying to achieve.
By the way, you could just call `[popover close]` when you want to close the popover.

**Comment by Mediajon** [comment]
Yes, right, I understand now how it works, thanks
